package koordinator;


/**
* koordinator/KoordinatorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Montag, 4. Mai 2015 21:58 Uhr MESZ
*/

abstract public class KoordinatorHelper
{
  private static String  _id = "IDL:koordinator/Koordinator:1.0";

  public static void insert (org.omg.CORBA.Any a, koordinator.Koordinator that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static koordinator.Koordinator extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (koordinator.KoordinatorHelper.id (), "Koordinator");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static koordinator.Koordinator read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_KoordinatorStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, koordinator.Koordinator value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static koordinator.Koordinator narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof koordinator.Koordinator)
      return (koordinator.Koordinator)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      koordinator._KoordinatorStub stub = new koordinator._KoordinatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static koordinator.Koordinator unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof koordinator.Koordinator)
      return (koordinator.Koordinator)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      koordinator._KoordinatorStub stub = new koordinator._KoordinatorStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
