package koordinator;


/**
* koordinator/ProzessIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Montag, 4. Mai 2015 21:58 Uhr MESZ
*/

public final class ProzessIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ProzessIdsHolder ()
  {
  }

  public ProzessIdsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = koordinator.ProzessIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    koordinator.ProzessIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return koordinator.ProzessIdsHelper.type ();
  }

}
