package koordinator;

/**
* koordinator/KoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Koordinator.idl
* Montag, 4. Mai 2015 21:58 Uhr MESZ
*/

public final class KoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public koordinator.Koordinator value = null;

  public KoordinatorHolder ()
  {
  }

  public KoordinatorHolder (koordinator.Koordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = koordinator.KoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    koordinator.KoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return koordinator.KoordinatorHelper.type ();
  }

}
