package client;


/**
* client/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Montag, 4. Mai 2015 21:53 Uhr MESZ
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
