package client;


/**
* client/ClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* Montag, 4. Mai 2015 21:53 Uhr MESZ
*/

public interface ClientOperations 
{
} // interface ClientOperations
