package ggTProcess;


/**
* ggTProcess/GgTProcess.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GgTProcess.idl
* Montag, 4. Mai 2015 21:54 Uhr MESZ
*/

public interface GgTProcess extends GgTProcessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GgTProcess
