package ggTProcess;


/**
* ggTProcess/GgTProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GgTProcess.idl
* Montag, 4. Mai 2015 21:54 Uhr MESZ
*/

public interface GgTProcessOperations 
{
  void setStartwerte (String linkeProzessId, String rechteProzessId, int startwertMi, int delayZeit, String monitorId);
  void rechnen (String prozessIdAbsender, int num);
  void markerAuswerten (int seqNr, String prozessIdAbsender);
  void beenden (String prozessIdAbsender);
} // interface GgTProcessOperations
