package ggTProcess;

/**
* ggTProcess/GgTProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GgTProcess.idl
* Montag, 4. Mai 2015 21:54 Uhr MESZ
*/

public final class GgTProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public ggTProcess.GgTProcess value = null;

  public GgTProcessHolder ()
  {
  }

  public GgTProcessHolder (ggTProcess.GgTProcess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ggTProcess.GgTProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ggTProcess.GgTProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ggTProcess.GgTProcessHelper.type ();
  }

}
