package ggTProcess;


/**
* ggTProcess/GgTProcessHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GgTProcess.idl
* Montag, 4. Mai 2015 21:54 Uhr MESZ
*/

abstract public class GgTProcessHelper
{
  private static String  _id = "IDL:ggTProcess/GgTProcess:1.0";

  public static void insert (org.omg.CORBA.Any a, ggTProcess.GgTProcess that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ggTProcess.GgTProcess extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ggTProcess.GgTProcessHelper.id (), "GgTProcess");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ggTProcess.GgTProcess read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GgTProcessStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ggTProcess.GgTProcess value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ggTProcess.GgTProcess narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ggTProcess.GgTProcess)
      return (ggTProcess.GgTProcess)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ggTProcess._GgTProcessStub stub = new ggTProcess._GgTProcessStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ggTProcess.GgTProcess unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ggTProcess.GgTProcess)
      return (ggTProcess.GgTProcess)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ggTProcess._GgTProcessStub stub = new ggTProcess._GgTProcessStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
