package ggTProcess;


/**
* ggTProcess/GgTProcessPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GgTProcess.idl
* Montag, 4. Mai 2015 21:54 Uhr MESZ
*/

public abstract class GgTProcessPOA extends org.omg.PortableServer.Servant
 implements ggTProcess.GgTProcessOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setStartwerte", new java.lang.Integer (0));
    _methods.put ("rechnen", new java.lang.Integer (1));
    _methods.put ("markerAuswerten", new java.lang.Integer (2));
    _methods.put ("beenden", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ggTProcess/GgTProcess/setStartwerte
       {
         String linkeProzessId = in.read_string ();
         String rechteProzessId = in.read_string ();
         int startwertMi = in.read_long ();
         int delayZeit = in.read_long ();
         String monitorId = in.read_string ();
         this.setStartwerte (linkeProzessId, rechteProzessId, startwertMi, delayZeit, monitorId);
         out = $rh.createReply();
         break;
       }

       case 1:  // ggTProcess/GgTProcess/rechnen
       {
         String prozessIdAbsender = in.read_string ();
         int num = in.read_long ();
         this.rechnen (prozessIdAbsender, num);
         out = $rh.createReply();
         break;
       }

       case 2:  // ggTProcess/GgTProcess/markerAuswerten
       {
         int seqNr = in.read_long ();
         String prozessIdAbsender = in.read_string ();
         this.markerAuswerten (seqNr, prozessIdAbsender);
         out = $rh.createReply();
         break;
       }

       case 3:  // ggTProcess/GgTProcess/beenden
       {
         String prozessIdAbsender = in.read_string ();
         this.beenden (prozessIdAbsender);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ggTProcess/GgTProcess:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GgTProcess _this() 
  {
    return GgTProcessHelper.narrow(
    super._this_object());
  }

  public GgTProcess _this(org.omg.CORBA.ORB orb) 
  {
    return GgTProcessHelper.narrow(
    super._this_object(orb));
  }


} // class GgTProcessPOA
