#ifndef __GgTProcess_idl__
#define __GgTProcess_idl__

module ggTProcess {
	interface GgTProcess {

		void setStartwerte(in string linkeProzessId, in string rechteProzessId, in long startwertMi, in long delayZeit, in string monitorId);

		void rechnen(in string prozessIdAbsender, in long num);

		void markerAuswerten(in long seqNr, in string prozessIdAbsender);

		void beenden(in string prozessIdAbsender);
	};
};

#endif