#ifndef __GgTProcess_idl__
#define __GgTProcess_idl__

module ggTProcess {
	interface GgTProcess;
};

module ggTProcess {
	interface GgTProcess {

		void setStartwerte(inout ::CORBA::WStringValue linkeProzessId, inout ::CORBA::WStringValue rechteProzessId, inout long long startwertMi, inout long delayZeit, inout ::CORBA::WStringValue monitorId);

		void rechnen(inout ::CORBA::WStringValue prozessIdAbsender, inout long long num);

		void markerAuswerten(inout long seqNr, inout ::CORBA::WStringValue prozessIdAbsender);

		void beenden(inout ::CORBA::WStringValue prozessIdAbsender);
	};
};

#endif