#ifndef __Koordinator_idl__
#define __Koordinator_idl__

module koordinator {
	interface Koordinator;
};

module koordinator {
	interface Koordinator {

		void anmelden(inout long typId, inout ::CORBA::WStringValue prozessId);

		void informieren(inout ::CORBA::WStringValue prozessId, inout long sequenzNr, inout boolean termStatus, inout long long letzteZahl);

		::org::omg::boxedRMI::seq1___CORBA__WStringValue getStarterIds();

		void berechnen(inout ::CORBA::WStringValue monitorId, inout long anzahlGgtLower, inout long anzahlGgtUpper, inout long delayZeitLower, inout long delayZeitUpper, inout long termAbfragePeriode, inout long gewuenschterGgt);

		void beenden(inout ::CORBA::WStringValue prozessIdAbsender);
	};
};

#endif