#ifndef __Monitor_idl__
#define __Monitor_idl__

#include "ProzessIds.idl"
#include "Startzahlen.idl"

module monitor {
	valuetype ProzessIds;
	valuetype Startzahlen;
	interface Monitor;
};

module monitor {
	interface Monitor {

		void ring(inout monitor::ProzessIds prozessIds);

		void startzahlen(inout monitor::Startzahlen startzahlen);

		void rechnen(inout U0020string prozessId, inout U0020string prozessIdAbsender, inout long long num);

		void terminieren(inout U0020string prozessId, inout U0020string prozessIdAbsender, inout boolean terminiere);

		void ergebnis(inout U0020string prozessId, inout long long num);
	};
};

#endif