#ifndef __Starter_idl__
#define __Starter_idl__

module starter {
	interface Starter {

		void setAnzahlProzesse(in long anzahl);

		void beenden(in string prozessIdAbsender);

		void beendeProzesse(in string prozessIdAbsender);
	};
};

#endif