package starter;


/**
* starter/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Starter.idl
* Montag, 4. Mai 2015 21:59 Uhr MESZ
*/

public interface StarterOperations 
{
  void setAnzahlProzesse (int anzahl);
  void beenden (String prozessIdAbsender);
  void beendeProzesse (String prozessIdAbsender);
} // interface StarterOperations
